### ISSUE TITLE
PHP 8.0/8.1 compatibility

### ISSUE THREAD

**Issue by mamsincl** [yireo/Yireo_Whoops#15]
Hi @jissereitsma,

It is any possibility to make the module php8.0/8.1 compatible?

Also, I am happy to help you out with it - just give me a shout.

Thanks,
R.

**Comment by jissereitsma** [comment]
Thanks for mentioning this. The code itself should work with PHP 8 without issues. But the composer requirement was there to force PHP 7, because of earlier Magento versions. That PHP requirement is removed now. Plus support for Magento 2.0, 2.1 and 2.2 is gone. The newest version of the module should be installable now. Does that work for you?

**Comment by mamsincl** [comment]
Hi Jisse,

Thanks for sorting it out and letting me know.
I am sure all the community also will appreciate it!

Bests,
R.
