### ISSUE TITLE
Can this module handle fatal errors or be registered earlier?

### ISSUE THREAD

**Issue by tylerssn** [yireo/Yireo_Whoops#8]
The module is installed and working, however, it does not appear to be configured to handle all errors on HTTP requests. For example, the following uses PHPs default exception:

```log
Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function getRequestFieldName() on null in /app/vendor/magento/module-ui/Component/Wrapper/UiComponent.php
```

**Comment by tylerssn** [comment]
Looks like this can be resolved (in >=PHP7) by configuring Whoops to catch `\Throwable` rather than `\Exception`. Fatal Errors use class `\Error` which is an instance of `\Throwable`

**Comment by jissereitsma** [comment]
I'm not sure if this is something the Whoops extension is able to fix. It seems that the Magento core function `catchException` (of class `Magento\Framework\App\Http`) is type-hinted with the argument `$exception` being an instance of `\Exception` and our interception plugin method simply follows this.

However, because the function is intercepted and because the current interception (M2.3) drops any kind of type hinting in the generated class, it might well be that this could be fixed in our plugin code. I have simply replaced the type `Exception` with `Throwable` and committed this. However, I'm unable to test this at this moment. If you want you can check out the `dev-master` version to see if it makes a difference for you.

**Comment by jissereitsma** [comment]
I've tested this and this seems to work. Will release a new build because of this.
